#vue:
#  image: suidu:vue
#  container_name: vue
#  volumes:
#    - ../src/web/vue/build:/vue/build:ro
#    - ../src/web/vue/config:/vue/config:ro
#    - ../src/web/vue/src:/vue/src:ro
#    - ../src/web/vue/build:/vue/build:ro
#  volumes_from:
#    - django
#  command: npm run build


mongodb:
  image: suidu:mongodb
  container_name: mongodb


scrapyd:
  image: suidu:scrapyd
  container_name: scrapyd
  volumes:
    - ./scrapyd:/scrapyd
  links:
    - mongodb
  ports:
    - "6800:6800"
  command: scrapyd


django:
  image: suidu:django
  container_name: django
  volumes:
    - ../src/web/django:/django:ro
    - ../src/web/dist/:/dist
  links:
    - mongodb
  expose:
    - "8000"
  command: gunicorn -c gunicorn_conf.py suidu.wsgi:application


#scrapy:
#  image: suidu:scrapy
#  container_name: scrapy
#  links:
#    - mongodb
#    - scrapyd
#  command: /bin/bash


nginx:
  image: suidu:nginx
  container_name: nginx
  links:
    - django
  ports:
    - "80:80"
  volumes_from:
    - django





